# Generated by Django 5.2.16 on 2026-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('exercise', models.CharField(max_length=40)),
                ('mode', models.CharField(max_length=16)),
                ('reason', models.CharField(max_length=16)),
                ('rep_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('cadence_rpm', models.FloatField(default=0.0)),
                ('cadence_windows', models.JSONField(default=list)),
                ('rep_durations_ms', models.JSONField(default=list)),
                ('feedback_counts', models.JSONField(default=dict)),
                ('scene_warning_counts', models.JSONField(default=dict)),
                ('calibration_samples', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
