# Generated by Django 5.2.16 on 2026-07-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    # O `LogEntry` do painel (SPEC-018) tem FK para o AUTH_USER_MODEL, e a `swappable_dependency`
    # dele aponta para a PRIMEIRA migration do app — que aqui é a 0001, criada quando ainda não
    # havia usuário nenhum (a conta nasceu na SPEC-011, nesta 0002). Sem esta linha o Django
    # tenta aplicar `admin.0001` antes de existir `api.user` e falha com "Related model
    # 'api.user' cannot be resolved". Só ordena; não muda operação nenhuma.
    run_before = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='SessionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_claim',
                'ordering': ['-created_at'],
            },
        ),
    ]
