# Generated by Django 5.2.16 on 2026-07-31 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('is_default', models.BooleanField(default=False, help_text='Plano de quem tem conta e não tem plano atribuído. Exatamente um.')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('daily_sessions', models.PositiveSmallIntegerField(default=0, help_text='Sessões por dia. 0 = ilimitado.')),
                ('session_min_s', models.PositiveSmallIntegerField(default=30)),
                ('session_max_s', models.PositiveSmallIntegerField(default=30)),
                ('countdown_max_s', models.PositiveSmallIntegerField(default=10)),
                ('allow_cloud', models.BooleanField(default=True)),
                ('history_limit', models.PositiveSmallIntegerField(default=50)),
                ('kcal_accumulation', models.BooleanField(default=False)),
                ('effects_enabled', models.BooleanField(default=False)),
                ('streak_protections_month', models.PositiveSmallIntegerField(default=0)),
                ('min_maturity', models.CharField(choices=[('validado', 'Validado (paridade + produção)'), ('calibrado', 'Calibrado (corpus real — Laboratório 🧪)')], default='validado', max_length=12)),
                ('daily_workout', models.BooleanField(default=False)),
                ('quota_message', models.TextField(blank=True, help_text='Mensagem da recusa por quota deste plano.')),
                ('flags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['ordem', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_slots', models.PositiveSmallIntegerField(default=3)),
                ('cloud_grace_ms', models.PositiveIntegerField(default=15000)),
                ('ticket_ttl_s', models.PositiveSmallIntegerField(default=45)),
                ('default_duration_s', models.PositiveSmallIntegerField(default=30)),
                ('default_countdown_s', models.PositiveSmallIntegerField(default=3)),
                ('series_min', models.PositiveSmallIntegerField(default=1)),
                ('series_max', models.PositiveSmallIntegerField(default=9)),
                ('series_default', models.PositiveSmallIntegerField(default=1)),
                ('reps_min', models.PositiveSmallIntegerField(default=5)),
                ('reps_max', models.PositiveSmallIntegerField(default=30)),
                ('reps_default', models.PositiveSmallIntegerField(default=15)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configuração do site',
                'db_table': 'site_config',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='plan_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.plan'),
        ),
    ]
