# Generated by Django 5.2.16 on 2026-07-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_planos_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('forca', 'Força'), ('core', 'Core'), ('mobilidade', 'Mobilidade')], default='cardio', max_length=16)),
                ('muscle_group', models.CharField(blank=True, max_length=60)),
                ('default_tip', models.TextField(blank=True, help_text='Estado vazio do card do treinador — ele nunca fica sem texto.')),
                ('main_angle', models.CharField(choices=[('arm_abduction', 'Abdução de braço'), ('none', 'Nenhum (mostra --)')], default='none', max_length=16)),
                ('demo_img', models.CharField(blank=True, max_length=200)),
                ('dot_color', models.CharField(default='#34d399', max_length=9)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True, help_text='Desligado some do catálogo E a admissão passa a recusar.')),
                ('met', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('maturity', models.CharField(choices=[('beta', 'Beta (só gerador sintético)'), ('calibrado', 'Calibrado (corpus real — Laboratório 🧪)'), ('validado', 'Validado (paridade + produção)')], default='beta', max_length=12)),
                ('min_plan', models.ForeignKey(blank=True, help_text='Vazio = todo mundo vê. Preenchido = exclusivo deste plano em diante (ordem).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_exercises', to='api.plan')),
            ],
            options={
                'db_table': 'exercise',
                'ordering': ['ordem', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseGuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('img', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_steps', to='api.exercise')),
            ],
            options={
                'db_table': 'exercise_guide_step',
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
