# Generated by Django 5.2.16 on 2026-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_catalogo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionresult',
            name='config_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
