# Generated by Django 5.2.16 on 2026-08-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_quota_do_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='scene_tip',
            field=models.TextField(blank=True, help_text='Vazio usa a frase padrão (em pé, celular na vertical, 2 m).'),
        ),
    ]
