# Generated by Django 5.2.16 on 2026-08-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_nomes_do_painel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_goal',
            field=models.CharField(choices=[('casual', 'Casual (1 sessão por dia)'), ('regular', 'Regular (2 sessões por dia)'), ('intenso', 'Intenso (4 sessões por dia)')], default='casual', max_length=12, verbose_name='meta diária'),
        ),
    ]
