# Generated by Django 5.2.16 on 2026-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_flexao_e_abdominal_para_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionresult',
            name='set_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='set_mode',
            field=models.CharField(default='livre', max_length=16),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='set_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionresult',
            name='target_reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
