# Generated by Django 5.2.16 on 2026-08-18 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_teto_da_serie_contada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGuideStepTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'en')], max_length=8)),
                ('texto', models.TextField(blank=True)),
                ('guide_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.exerciseguidestep')),
            ],
            options={
                'verbose_name': 'tradução de passo do guia',
                'verbose_name_plural': 'traduções de passo do guia',
                'db_table': 'exercise_guide_step_translation',
                'ordering': ['guide_step_id', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('guide_step', 'locale'), name='uniq_guide_step_translation_locale')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'en')], max_length=8)),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('muscle_group', models.CharField(blank=True, max_length=60)),
                ('default_tip', models.TextField(blank=True)),
                ('scene_tip', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.exercise')),
            ],
            options={
                'verbose_name': 'tradução de exercício',
                'verbose_name_plural': 'traduções de exercício',
                'db_table': 'exercise_translation',
                'ordering': ['exercise_id', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('exercise', 'locale'), name='uniq_exercise_translation_locale')],
            },
        ),
        migrations.CreateModel(
            name='PlanTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'en')], max_length=8)),
                ('nome', models.CharField(blank=True, max_length=60)),
                ('quota_message', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.plan')),
            ],
            options={
                'verbose_name': 'tradução de plano',
                'verbose_name_plural': 'traduções de plano',
                'db_table': 'plan_translation',
                'ordering': ['plan_id', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'locale'), name='uniq_plan_translation_locale')],
            },
        ),
    ]
