# Generated by Django 5.2.16 on 2026-08-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_traducoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='url_slug',
            field=models.SlugField(blank=True, help_text='Vazio usa o slug técnico. Mudar troca o endereço de uma página já indexada.', max_length=60, verbose_name='slug da URL pública'),
        ),
        migrations.AddField(
            model_name='exercisetranslation',
            name='url_slug',
            field=models.SlugField(blank=True, max_length=60, verbose_name='slug da URL pública'),
        ),
    ]
